"""Adiciona campo is_subscriber no modelo User

Revision ID: af71a703a667
Revises: 13f8a7cf114f
Create Date: 2024-10-06 11:45:02.454685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af71a703a667'
down_revision = '13f8a7cf114f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_subscriber', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_subscriber')

    # ### end Alembic commands ###
